### ISSUE TITLE
Block a PR if certain strings aren't localized in each language

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeTransfer-iOS-CI#103]
PRs shouldn't be merged if some of the keys are missing a localized variant. It would be great if we can check this through Danger and throw an error for the keys that miss localization.

**Comment by AvdLee** [comment]
@amirdew I would love to get your input on this one. I think that your tool can be from great value in making this work!

**Comment by amirdew** [comment]
Yeah, I was going to open PR for it.
in `scripts/localization.sh` file we have 

```bash
    # Compare keys to the development language
    "${SRCROOT}/scripts/Localizable" validate "${INPUT_FILE_PATH}" -d="${DEVELOPMENT_LANGUAGE}";
    # Make an empty file since the Build Rule expects an output for every input.
    touch "${OUTPUT_FILE_PATH}";
```

I guess we just want this to throw an error on CI and show a warning on local, right?
Didn't check but I think it's possible to do in the bash script itself

**Comment by AvdLee** [comment]
@amirdew yeah exactly! That should definitely be possible. Something to figure out as part of this issue 👌
