### ISSUE TITLE
Verify re-run tests that succeed after failure are not blocking PRs

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeTransfer-iOS-CI#105]
A test can be re-run after failure and succeeding:
![image](https://user-images.githubusercontent.com/4329185/141986810-5384bf1d-b97f-4180-84c9-364754c63dd4.png)

Though, it looks like PRs still get blocked by a test failure being reported. We should look into this.

It's best to reproduce this locally by writing a test that fails 50/50

Example log:
[apps_6bee37a5a2a41cdb_47ac49f1-faed-438b-a7e7-b1bb900d7b0a-full.txt.zip](https://github.com/WeTransfer/WeTransfer-iOS-CI/files/7546321/apps_6bee37a5a2a41cdb_47ac49f1-faed-438b-a7e7-b1bb900d7b0a-full.txt.zip)

**Comment by BasThomas** [comment]
Would be great if we can (still) leave a Danger warning indicating that a test failed the first/second time, but succeeded the next time, to not hide the fact that tests may be indeterministic.

**Comment by AvdLee** [comment]
> Would be great if we can (still) leave a Danger warning indicating that a test failed the first/second time, but succeeded the next time, to not hide the fact that tests may be indeterministic.

Just for completeness, I implemented that here: https://github.com/WeTransfer/WeTransfer-iOS-CI/pull/109
