### ISSUE TITLE
Build errors are not visible in GitHub PRs

### ISSUE THREAD

**Issue by kevinrenskers** [WeTransfer/WeTransfer-iOS-CI#123]
For example in https://github.com/WeTransfer/WeTransfer-iOS-SDK/pull/474, the second commit ("Remove the test") had a build error causing the tests to not even run. But the build error was never visible in the PR, so I had to ask someone to dig into Bitrise to see what the problem was.

**Comment by AvdLee** [comment]
This is solved!
