### ISSUE TITLE
Bitrise can report "green" even when the build fails

### ISSUE THREAD

**Issue by BasThomas** [WeTransfer/WeTransfer-iOS-CI#145]
Also, Danger has been having issues reporting the actual errors that happen. Is that something we can improve?

In some pull requests:

- Bitrise was green
- Danger was red, but only "because the build failed"

<img width="455" alt="image" src="https://user-images.githubusercontent.com/4190298/162715875-9c214751-acc4-4267-b5d0-4ae5ce6dd2c8.png">

Whereas the actual errors occur in e.g. a test target where things don't compile because the API was changed.

**Comment by neodym** [comment]
Are we keeping this as an Issue type here, or do we create a ticket out of it for planing?

**Comment by AvdLee** [comment]
@BasThomas yes, I was actually doing that right now!
