### ISSUE TITLE
Comment on issues & PRs: "This is released in"

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeTransfer-iOS-CI#59]
It would be great to have automatically posted comments on issues and PRs with the release URL that contained the change.

This will help our open-source projects to be more transparent, as well as our QA team to know something is ready to be tested.

### Where to implement this?
As our https://github.com/WeTransfer/ChangelogProducer contains a lot of logic to talk with GitHub already, it's probably nice to make it a bit more advanced and be able to post comments as well.

We also need this for the stale issues implementation (#58), which is a win-win.

### Examples
See [this](https://github.com/fastlane/fastlane/issues/11971#issuecomment-569772719) comment:
![image](https://user-images.githubusercontent.com/4329185/71886799-1eef8080-313d-11ea-9bd2-4de86064fe9a.png)

This is done by this class: https://github.com/fastlane/issue-bot/blob/457348717d99e5ffde34ca1619e7253ed51ec172/bot.rb

**Comment by AvdLee** [comment]
Looking at the Fastlane implementation we can learn from [this](https://github.com/fastlane/issue-bot/blob/master/bot.rb#L261) piece of code:

```ruby
def mark_as_released(pr, prs_to_releases)
  version = prs_to_releases[pr.number.to_s]
  release_url = "https://github.com/#{SLUG}/releases/tag/#{version}"

  logger.info("Marking #{pr.number} as having been released in version #{version}")

  # This doesn't wind up modifying the in-memory object, so we will still find this label applied
  # when we check for it in the next step.
  client.remove_label(SLUG, pr.number, INCLUDED_IN_NEXT_RELEASE) if has_label?(pr, INCLUDED_IN_NEXT_RELEASE)
  client.add_labels_to_an_issue(SLUG, pr.number, [RELEASED])
  client.add_comment(SLUG, pr.number, "Congratulations! :tada: This was released as part of [_fastlane_ #{version}](#{release_url}) :rocket:")

  issue_number = referenced_issue_number?(pr)
  if issue_number
    logger.info("Adding a comment to the issue #{issue_number} that pull request #{pr.number} has been released")

    body = []
    body << "The pull request ##{pr.number} that closed this issue was merged and released as part of [_fastlane_ #{version}](#{release_url}) :rocket:"
    body << "Please let us know if the functionality works as expected as a reply here. If it does not, please open a new issue. Thanks!"
    client.add_comment(SLUG, issue_number, body.join("\n"))
  end

  smart_sleep
end
```

- We don't need the labels
- We comment on the PR that it's been released
- We take the linked issues and comment there as well that it's merged with PR_ID and released in RELEASE_URL

# When is this triggered?
We could do this in two ways:

- Create a cron job that goes over the latest X releases and comment linked issues
- Make this part of the release process

The latter seems more efficient as we know there has actually been a new release. Also, it feels kind of logic to make this part of the release process.

# Where to implement this?
Right now, we have the release generation in Ruby and the changelog generation written in Swift inside the ChangelogProducer. As we decided earlier before, we'd like to be future proof and make the code readable for fellow colleagues. As Swift is our main language, it kind of makes sense to write this in Swift as part of the ChangelogProducer.

However, "ChangelogProducer" implies generating changelogs only. Therefore, we should consider changing the name to something like "GitBuddy". It could look as follows:

```
gitbuddy --help
OVERVIEW: Manage your GitHub repositories with ease

USAGE: gitbuddy <commands>

COMMANDS:
  changelog         Generate a changelog for a range between two tags
  stale-processing  Process stale issues, add labels and needed comments
  release           Create a new release including a changelog and publish comments on related issues
  help              Display available options
```

This creates three new commands, let's go over them.

## Changelog
This command will allow us to generate a changelog. It's basically the base we have right now inside the ChangelogProducer. It could be that users of our project only need a generated changelog.

```
gitbuddy changelog --help
OVERVIEW: Create a changelog for GitHub repositories

USAGE: gitbuddy changelog <options>

OPTIONS:
  --baseBranch, -b  The base branch to compare with
  --sinceTag, -s    The tag to use as a base
  --verbose         Show extra logging for debugging purposes
  --help            Display available options
```

## Stale-processing
This will go over all the issues in the repository and should be integrated into a CI cron job to make sure it's regularly updating stale issues.

For MVP, we should lead this implementation. In future versions, we could allow a configuration file containing stuff like label names, max-issues to handle or ignoring issues based on labels.

```
gitbuddy stale-processing --help
OVERVIEW: Process stale issues, add labels and needed comments

USAGE: gitbuddy stale-processing <options>

OPTIONS:
  --verbose         Show extra logging for debugging purposes
  --help            Display available options
```

## Release
This is basically the release flow we have now in Ruby and inside the ChangelogProducer. It creates a new release on Github for the latest generated tag/input tag and includes the generated changelog. It also allows to update the `Changelog.md` if a path is provided.

```
gitbuddy release --help
OVERVIEW: Create a new release including a changelog and publish comments on related issues

USAGE: gitbuddy release <options>

OPTIONS:
  --changelog-path  The path to the Changelog to update it with the latest changes
  --skip-comments   Disable commenting on issues and PRs about the new release     
  --verbose         Show extra logging for debugging purposes
  --help            Display available options
```

**Comment by kairadiagne** [comment]
Good job on the writeup! It is very clear. I think it is a good idea to turn `ChangeLogProducer` into a tool that helps us achieve those specific tasks we need to manage our GitHub repos. I have some questions regarding your ideal solution:

- When you think about any non-Swift project within WeTransfer. What are the requirements for that to happen? E.g. would our tool look very different.
- With regards to those requirements. Is there anything we should already take into consideration right now?

**Comment by AvdLee** [comment]
Thanks, @kairadiagne! I'm glad you agree with me that this is a good direction to take.

> When you think about any non-Swift project within WeTransfer. What are the requirements for that to happen? E.g. would our tool look very different.

The main thing to consider here is that it should be easy to understand how this can be implemented in other CI tools like Travis as Bitrise is mobile-oriented only. Therefore, the "GitBuddy" should be CI independent. Other than that, we should make it work with any GitHub repository and we're good.

Another thing is JIRA issues as not everyone is working with GitHub issues. However, I think that the focus should rely mainly on the open-source projects which all use GitHub issues.

> With regards to those requirements. Is there anything we should already take into consideration right now?

I don't really think so other than the points I just wrote down.

**Comment by kairadiagne** [comment]
Keeping `GitBuddy` CI independent makes a lot of sense. I agree that JIRA is out of scope.

**Comment by AvdLee** [comment]
As preparation for the actual implementation I've been working on the missing endpoints in the Octokit framework:

- https://github.com/nerdishbynature/octokit.swift/pull/94
- https://github.com/nerdishbynature/octokit.swift/pull/95

We will need those to be able to implement the above proposal.

**Comment by AvdLee** [comment]
I decided to not implement the stale issue management as there are quite some nice options available already, that work with GitHub actions: https://github.com/WeTransfer/frontend/actions/runs/35268483/workflow

WeTransfer/Frontend is using this already and it seems to work great. No need to spent time on this and rebuild everything

**Comment by AvdLee** [comment]
This is now working by using GitBuddy!
