### ISSUE TITLE
How to add beta deployment support in workflow ?

### ISSUE THREAD

**Issue by tariq235** [WeTransfer/WeTransfer-iOS-CI#69]
Is there any plan to add a beta deployment support on existing or new workflow ? If not, can you guide how to refactor existing WeTransfer-iOS-CI ?

**Comment by AvdLee** [comment]
@tariq235 sorry, but I don't think this is matching the scope of our framework at this point. You can setup `deliver` with `gym` in fastlane yourself to solve that! 🙂
