### ISSUE TITLE
[Danger] Replace custom rules with SwiftLint versions

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeTransfer-iOS-CI#82]
To ensure the same outcome locally in Xcode as when CI completes. Currently, we only see issues once CI succeeded which is a lose of time.

**Comment by kevinrenskers** [comment]
It's not possible to create a "proper" final_class rule, which would check if a class is actually subclassed, as custom rules can only be built using a regex :( But since that's basically the same as https://github.com/WeTransfer/Danger/blob/master/Dangerfile does, that should be okay I guess.

**Comment by AvdLee** [comment]
> It's not possible to create a "proper" final_class rule, which would check if a class is actually subclassed, as custom rules can only be built using a regex :( But since that's basically the same as our current implementation does, that should be okay I guess.

I agree, that would be better than our current rule since we would get back feedback at build time instead of PR time

**Comment by AvdLee** [comment]
Closing this since I guess this is done!
