### ISSUE TITLE
[CI] Add an option to automatically merge PRs on green

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeTransfer-iOS-CI#84]
Automatically merging PRs would speed up quite some cases

**Comment by AvdLee** [comment]
@BasThomas would love to get your ideas for this! Any experience with solutions?

**Comment by AvdLee** [comment]
Also nice: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request

**Comment by BasThomas** [comment]
Haven't implemented something like this in the past. But let me take a look at it; especially the built-in GitHub automerge.

**Comment by AvdLee** [comment]
This is fixed by enabling auto merge on our repositories.

**Comment by AvdLee** [comment]
Reopening since auto-merge is also merging for red PRs, which is not good. It should really only merge when CI is green!

**Comment by BasThomas** [comment]
Oh noes! 🙈

**Comment by AvdLee** [comment]
It seems to be fixed by setting restrictions towards merging, e.g. Danger and Bitrise need to succeed.
This is now enabled:
![image](https://user-images.githubusercontent.com/4329185/140482481-3a54fd01-02f9-4b56-8d36-116f053df2fc.png)

The downside is that manual merging isn't possible either when CI failed. Though, we really don't want to auto-merge when checks fail. Let's see whether these restrictions really become a problem.

**Comment by AvdLee** [comment]
Closing for now, lets reopen if we need to revisit our implementation.
