### ISSUE TITLE
[CI] Improve build delivery

### ISSUE THREAD

**Issue by AvdLee** [WeTransfer/WeTransfer-iOS-CI#86]
There are a few downsides we have right now with our release train that depends on build creation from develop:

- The actual release build can be different from the tested TestFlight build
- We create a build twice, which means a CI train running twice, which is less efficient
- The release notes are created after the build was submitted. There's a small timespan between the build trigger and the release note creation in which new PRs can be merged, indicating that something is fixed while its not

We should fix this by improving our release train:

- [ ] Use the same build for submission as for TestFlight delivery
- [ ] Create the release notes based on the date of starting the build. In other words, the date of the latest commit used in the tag
- [ ] Get rid of the endless release notes. It would be much better to only have GitHub releases for builds that actually made it into the App Store

**Comment by AvdLee** [comment]
@BasThomas curious to hear your ideas! For example; did you have Debug/TestFlight only debug-menus? And if so, how did you enable them in a build that would later be released to the App Store. In other words; how would you prevent a debug menu from showing up in a release build?

Any other thoughts in regards to automatically releasing builds would be very welcome!

**Comment by kevinrenskers** [comment]
What Last.fm does, is that the debug menu is based on the user information. So you need to be logged in, which is a bit of a problem for our app of course, since we want to be able to set the environment before logging in. You used to be able to detect if you're running on the App Store or TestFlight, maybe that's still possible? If so, that would allow us to only deal with one build, and "promote" a TF build to the AS when approved.

**Comment by BasThomas** [comment]
> @BasThomas curious to hear your ideas! For example; did you have Debug/TestFlight only debug-menus? And if so, how did you enable them in a build that would later be released to the App Store. In other words; how would you prevent a debug menu from showing up in a release build?

If I remember correctly, we had a debug menu at XING using a compiler directive `#if TESTFLIGHT` or `#if BETA`, something like that. I see we have an `#if TESTFLIGHT`. I think that'd be the safest way, as all of that should not be compiled at all in other environments.

With that, we'd have multiple targets (alpha, beta, release candidate, live). That way, we'd always have to same commit for all targets, but still different products in the end.

**Comment by AvdLee** [comment]
@kevinrenskers yeah, it's interesting to think of solutions like this! I'm afraid to implement a `isRunningTestFlight` check that in a future iOS update suddenly enables debug mode for all our users because our expectations are no longer valid 🤔

**Comment by AvdLee** [comment]
@BasThomas that's what we have now, indeed, but the downside is having to create a new build for release which is what we want to move away from 🤔

**Comment by AvdLee** [comment]
What if we create a iOS Settings configuration that if you fill in a certain keyword, debug mode gets enabled? 🤔

**Comment by kevinrenskers** [comment]
Like a secret code, up up down down left right left right hahaha

**Comment by kevinrenskers** [comment]
The old version of the Last.fm app did the same by the way: if you searched for a particular secret string, it would enable debug mode too. Worked really well :)

**Comment by AvdLee** [comment]
> The old version of the Last.fm app did the same by the way: if you searched for a particular secret string, it would enable debug mode too. Worked really well :)

Yeah, exactly! Something like that. Maybe combined with `@wetransfer.com` addresses giving debug mode access?

**Comment by kevinrenskers** [comment]
That should work. Yeah because on debug builds we can just always enable the debug menu, so I can login on the production server just fine. And on release builds, it defaults to the production server anyway, you can login, then access the debug menu 👍

**Comment by AvdLee** [comment]
I wonder if there are any scenarios in which we want to access the debug menu before logging in. If we just use the `@wetransfer.com` check, we have a simple and safe check, which is easy to implement!

**Comment by kevinrenskers** [comment]
> I wonder if there are any scenarios in which we want to access the debug menu before logging in. 

On debug builds: absolutely! On release builds: I've never had a need for that, but I absolutely need the debug menu in debug builds or I can't login to the app.

**Comment by amirdew** [comment]
> the downside is having to create a new build for release which is what we want to move away from 🤔

Can we create both builds at the same time? and upload both of them to test flight? QA can use the prod build for most tests and use the dynamic-env build when it's not possible with prod build

**Comment by AvdLee** [comment]
@amirdew we could obviously, but that would slow down CI quite a bit and make it even more confusing in terms of which build is tested, which one is final, etc. It would not be my preferred route!

I guess we can start with an email-based debug menu enabler. Another cool idea that we found [on Twitter](https://twitter.com/N1C0_MUC/status/1460278131089195011?s=20) is to use another app that accesses the same app group identifier and enables the debug menu through it. Though; it requires another app to maintain, so not entirely sure if this is what we want.

**Comment by kairadiagne** [comment]
Should we check in with a security engineer to get their perspective on this?

**Comment by AvdLee** [comment]
> Should we check in with a security engineer to get their perspective on this?

Can you elaborate why you think that would add value here?

**Comment by kairadiagne** [comment]
> > Should we check in with a security engineer to get their perspective on this?
> 
> Can you elaborate why you think that would add value here?

Were deciding how we can ship builds using the debug menu and thus also things that we might don't want to include in the binary. And we are looking at how to do this in a secure way, via the user email or separate app. So besides build delivery this also touches security. A security engineer might have a different perspective which I think can be valuable to hear before we finalize the solution. I think it doesn't hurt to try. Let me know what you think.

**Comment by AvdLee** [comment]
@kairadiagne thanks for clarifying, that makes sense! Let's loop them in once we've got a clearer direction we can share

**Comment by AvdLee** [comment]
So; since security replied as follows:

> Hi Antoine We should remove any code that is not relevant to our production builds. We have produced a policy that speaks to this here https://www.notion.so/wetransfer/Access-Control-Policy-3e916ef5aa9e4e74b1f8c5588bf011c8, under the last section Access to Program Source Code.
We are not yet enforcing this policy , as we have a lot of work to get to this requirement, but the general rule is, remove anything that is not required. Any deviations from this we will need to document and track.
The justification is that attackers may decompile the iOS app or settings and be able to obtain resource or hosts for staging or dev environment that help them plan further attacks.
We want to prevent data leakage where ever we can.

We need to keep two build deliveries in place. This means we can stay close to what we have today. Yet; we still need to improve two things:

- [ ] Get rid of the endless list of release notes by deleting tags that aren't actually released
- [ ] Make sure the release notes are accurate and don't contain changes that aren't actually in the build

**Comment by AvdLee** [comment]
Collect 6.1.4 was reviewed by QA while using the build that was actually submitted. This takes away one of our biggest downsides of having two builds and creates confidence that we release a stable build 💪

**Comment by AvdLee** [comment]
Delete older releases can be inspired by: https://github.com/dev-drprasad/delete-older-releases/blob/master/index.js
